name: deploy-infra-as-code-test

on: [workflow_dispatch]

permissions:
  id-token: write
  contents: read

env:
    AZURE_RESOURCEGROUP_NAME: agustin-gabrielli-rg

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Deploy Bicep files
      run: |
        # Temporary fix for bicep CLI bug in latest az cli version
        az config set bicep.use_binary_from_path=false
        az deployment group create \
          --name deploy-infra-as-code-test-${{ github.run_number }} \
          --resource-group ${{ env.AZURE_RESOURCEGROUP_NAME }} \
          --template-file main.bicep \
          --parameters main.bicepparam