name: deploy-infra-as-code-test
concurrency: deploy-infra-as-code-test # This is used to prevent concurrent runs of the same workflow

on: 
  push:
    branches:
      - main
    paths:
      - 'deploy/**' # Only trigger the workflow if a file in the deploy folder is changed
  # [workflow_dispatch] # This is used to trigger the workflow manually in Github

permissions:
  id-token: write
  contents: read

env:
    AZURE_RESOURCEGROUP_NAME: agustin-gabrielli-rg

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 # Checkout (get the code) from the repo to the runner
    - uses: azure/login@v1 # Login to Azure using the service principal
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Deploy Bicep files
      run: |
        # Temporary fix for bicep CLI bug in latest az cli version
        az config set bicep.use_binary_from_path=false
        az deployment group create \
          --name deploy-infra-as-code-test-${{ github.run_number }} \
          --resource-group ${{ env.AZURE_RESOURCEGROUP_NAME }} \
          --template-file ./deploy/main.bicep \
          --parameters ./deploy/main.bicepparam